version: "3"

services:
  website:
    image: ridoy235/elitbuzz:school_website_v2
    pull_policy: always
    # volumes: 
    #   - AllFiles:/app/AllFiles
    #network_mode: host
    ports:
      - "3001:3000"
      # - "8089:3000"
    restart: unless-stopped
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - DATABASE_URL=${DATABASE_URL}

# volumes:
#   AllFiles: